Develop
LinSky0323/wehelp_stage2 pull request #5
Opened 2024-06-05 16:54 UTC by LinSky0323

老師您好，我是陳聖鎧，我來交第2週作業：
http://13.114.168.77:8000/
我嘗試用用看react(之前僅看過影片沒有做過東西)，我用了useState,useEffect,useRef而已，其他hook跟套件都沒有使用，可能其中還有一些有問題的地方但是我不知道/沒有發現的，麻煩老師了
感謝您!!!!!

2024-06-05 21:18 UTC, cwpeng requested changes
Before we talk about React, as a front-end engineer, take care of all the layout details first: color, size, border and spacing.
![13 114 168 77_8000_](https://github.com/LinSky0323/wehelp_stage2/assets/6104683/0a7efa51-65f8-4f02-9e9d-bac01b65d564)

2024-06-06 07:11 UTC, LinSky0323 commented
老師不好意思 有做修正了 要在麻煩你了

2024-06-06 07:29 UTC, cwpeng requested changes
Cannot do any keyword search.

2024-06-06 07:54 UTC, LinSky0323 commented
Tescher, I'm so sorry.I 不小心 modify my fetch url & lost 'api' three word.
I fix ok & try it OK ,please teacher check it.

2024-06-06 08:21 UTC, cwpeng approved these changes
OK. Done.

2024-06-06 08:24 UTC, merged