Develop
LinSky0323/wehelp_stage2 pull request #7
Opened 2024-06-18 17:12 UTC by LinSky0323

老師好，我是聖鎧，我來交第4週作業：
http://18.176.26.217:8000/
http://18.176.26.217:8000/attraction/10
麻煩老師了

2024-06-19 09:22 UTC, cwpeng requested changes
- Based on API specs, we should use request body for sending JSON data to the backend.
- Height of navigation bar in homepage is too large.

2024-06-19 10:00 UTC, LinSky0323 commented
老師有把CSS調整過了，然後註冊跟登入的fetch有用body去傳送，另外加了點前端接收時的檢查
再麻煩老師了

2024-06-19 19:39 UTC, cwpeng requested changes
I try to reload homepage and it's broken.

2024-06-19 23:06 UTC, LinSky0323 commented
那個...請問老師你是什麼做了什麼特定的操作時候他壞掉了？
我看錯誤資訊像是資料庫那邊的連線掛掉了，可是我重掛uvicorn之後，自己測試都正常沒有壞掉(我忘記在重掛uvicorn之前先去資料庫檢查連線了QQ)
目前重啟過我看是正常的，麻煩老師看看了

2024-06-20 04:37 UTC, cwpeng approved these changes
OK. Done.

I just view and reload homepage and then, get error, nothing else.

2024-06-20 05:30 UTC, merged